# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tome < Formula
  desc "CLI Wrapper Tool for Turning a Folder of Scripts into an SDK"
  homepage "https://github.com/zph/tome"
  version "0.0.0-rc20"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zph/tome/releases/download/v0.0.0-rc20/tome_0.0.0-rc20_darwin_arm64.tar.gz"
      sha256 "a0fca45ea5a9c37a21ad3b343f38004cd15dc028f207599752f075a64fa07784"

      def install
        bin.install "tome"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zph/tome/releases/download/v0.0.0-rc20/tome_0.0.0-rc20_darwin_amd64.tar.gz"
      sha256 "3dcf8d377a4e8c18538be07b95105596607f99be95e7426c65eb3353d35c9e34"

      def install
        bin.install "tome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zph/tome/releases/download/v0.0.0-rc20/tome_0.0.0-rc20_linux_amd64.tar.gz"
      sha256 "03a4bac9640bd2be8bf06727b47c2ee14acb087f4749ac496461611094f2e463"

      def install
        bin.install "tome"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zph/tome/releases/download/v0.0.0-rc20/tome_0.0.0-rc20_linux_arm64.tar.gz"
      sha256 "99771f354dba5088b423732311f5b771e0a328cf306f371d2fbca70f98ca93a2"

      def install
        bin.install "tome"
      end
    end
  end
end
