# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tome < Formula
  desc "CLI Wrapper Tool for Turning a Folder of Scripts into an SDK"
  homepage "https://github.com/zph/tome"
  version "0.0.0-rc5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zph/tome/releases/download/v0.0.0-rc5/tome_0.0.0-rc5_darwin_arm64.tar.gz"
      sha256 "6135e6e96c69bd2bb9fa8dd1987eb7783149efc7f7f5821694ba4108a8191f91"

      def install
        bin.install "tome"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zph/tome/releases/download/v0.0.0-rc5/tome_0.0.0-rc5_darwin_amd64.tar.gz"
      sha256 "9204e603cf284203707745348ccefeaf7897d48473a64cb961915f4d59e866be"

      def install
        bin.install "tome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zph/tome/releases/download/v0.0.0-rc5/tome_0.0.0-rc5_linux_amd64.tar.gz"
      sha256 "c1da06a1b2509ad8f24befba29d4e642b56baab102df114340a66185784af749"

      def install
        bin.install "tome"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zph/tome/releases/download/v0.0.0-rc5/tome_0.0.0-rc5_linux_arm64.tar.gz"
      sha256 "56eb1324fca518974b01e6a07f7ecd95f08c0610772f6afa787d1ad55c731e5d"

      def install
        bin.install "tome"
      end
    end
  end
end
