on: [push]
name: tests
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: e2e-test
        run: |
          sudo apt-get install zsh fish -y
          echo "testing bash"
          bash scripts/e2e-test.sh bash
          echo "testing zsh"
          zsh scripts/e2e-test.sh zsh
          echo "testing fish"
          fish scripts/e2e-test.fish fish
          echo "testing run"
          zsh scripts/e2e-test-run.sh
